apiVersion: v1
kind: Service
metadata:
  name: rest-api-mahasiswa-service
  namespace: mahasiswa-app
spec:
  selector:
    app: rest-api
  ports:
  - protocol: TCP
    port: 80 # Port yang diexpose oleh Service
    targetPort: 3000 # Port container (sesuai ENV PORT di ConfigMap/Deployment)
  type: LoadBalancer # Atau NodePort untuk akses eksternal, tergantung environment K8s Anda