apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-main-pvc
  namespace: mahasiswa-app # Pastikan namespace sama
spec:
  accessModes:
    - ReadWriteOnce # Umum untuk database
  resources:
    requests:
      storage: 2Gi # Sesuaikan ukuran jika perlu (misalnya, 1Gi, 5Gi)
