# values-kafka.yaml
replicaCount: 1 # Untuk development, 1 broker cukup
# zookeeper: # Chart kafka bitnami akan otomatis deploy zookeeper jika tidak didefinisikan externalZookeeperServers
#   replicaCount: 1
#   persistence:
#     size: 1Gi
persistence:
  enabled: true
  size: 2Gi # Penyimpanan untuk Kafka broker
# externalAccess: # Jika perlu akses dari luar cluster, bisa dikonfigurasi di sini
#   enabled: false
#   service:
#     type: LoadBalancer
#     ports:
#       external: 9094
autoCreateTopicsEnable: true # Bisa juga false, lalu buat topic manual
# Contoh membuat topic "mahasiswa_events" saat instalasi (formatnya mungkin berbeda antar versi chart)
# Provisioning.topics:
#  - name: mahasiswa_events
#    partitions: 3
#    replicationFactor: 1
#    config:
#      retention.ms: "604800000"
