apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: local-path      
  accessModes:
    - ReadWriteOnce                
  resources:
    requests:
      storage: 3Gi                  
