apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # ‒‒‒ (Job 'prometheus' untuk self-scrape) ‒‒‒
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # ‒‒‒ Job baru: node-exporter ‒‒‒
      - job_name: 'node-exporter'
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: 'node-exporter'
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: replace
            target_label: __address__
            regex: 'metrics'
            replacement: '${1}:9100'
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            regex: '(.+)'
            replacement: '${1}:9100'

      # ‒‒‒ Job baru: kube-state-metrics ‒‒‒
      - job_name: 'kube-state-metrics'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            action: keep
            regex: 'monitoring;kube-state-metrics;http-metrics'

      # Scrape kubelet’s cAdvisor endpoint ──
      - job_name: 'kubelet-cadvisor'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        metrics_path: /metrics/cadvisor

        relabel_configs:
          - source_labels: [__meta_kubernetes_node_condition_ready]
            action: keep
            regex: "true"

          - target_label: __address__
            replacement: 10.43.0.1:443  

          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: __metrics_path__
            # When a node is named “node-1”, this expands to:
            #    /api/v1/nodes/node-1/proxy/metrics/cadvisor
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
