# values-postgres-main.yaml
global:
  postgresql:
    auth:
      postgresPassword: "password"
      username: "user"
      database: "mahasiswa_db"
primary:
  persistence:
    enabled: true
    size: 2Gi 
