apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubelet'
        scheme: https
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: node
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            action: replace
            target_label: __address__
            regex: '(.+)'
            replacement: '${1}:10250'

          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: node

      - job_name: 'cadvisor'
        scheme: https
        metrics_path: /metrics/cadvisor
        kubernetes_sd_configs:
          - role: node
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            action: replace
            target_label: __address__
            regex: '(.+)'
            replacement: '${1}:10250'

          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: node

      - job_name: 'k8apiserver'
        scheme: https
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            action: keep
            regex: 'default;kubernetes;https'
          - source_labels: [__meta_kubernetes_endpoint_address_target_ref_name, __meta_kubernetes_endpoint_port_name]
            action: replace
            target_label: __address__
            regex: '(.+);https'
            replacement: '${1}:6443'

      - job_name: 'k8services'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
            action: drop
            regex: 'default;kubernetes'
          - source_labels:
              - __meta_kubernetes_namespace
            regex: 'default'
            action: keep
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: job

      - job_name: 'k8pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: 'metrics'
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: job
